pool:
  vmImage: 'Ubuntu 20.04'

trigger:
  branches:
    include:
      - master
      - feature/*
      - bug/*
  tags:
    include:
      - v*

variables:
  imageName: 'datastudio'
  major: 0
  minor: 0
  patch: 2

pr:
  branches:
    include:
      - master

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'

  - script: |
      pip install awscli
    displayName: 'Environment Preparation'

  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Configuring the node tool'

  - task: Npm@1
    displayName: 'Install all node modules'
    inputs:
      command: install

  - script: |
      npm run test
    displayName: 'Running tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'build/test-results/**/TESTS-*.xml'
      testRunTitle: 'DX26 test results'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    displayName: 'Publishing code coverage'
    inputs:
      #          codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/build/test-results/clover.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/build/test-results/Icov-report'

  - script: |
      npm run webpack:prod --prod
    displayName: 'Build'

  - script: |
      docker build -t $DOCKER_REPO/$(imageName):v$(major).$(minor).$(patch) .
    condition: eq(variables['Build.Reason'], 'PullRequest') # Currently running it only while a PR is created
    env:
      DOCKER_REPO: $(DOCKER_REPO)
    displayName: 'Build docker image and tag it'
# TODO: Publishing docker image
# TODO: Implementing CD
