version: '3.3'
services:
  app:
    image: 'dx26-io/data-studio:v1.0.0'
    container_name: data-studio
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      - NGINX_PROXY=http://localhost:8002
      - NGINX_PORT=80
      - NGINX_HOST=localhost
    build:
      context: '.'
      args:
        - API_URL=http://localhost:8002/
    ports:
      - 80:80
      - 443:443
