version: '3.3'
services:
  app:
    image: 'dx26-io/data-studio:v1.0.0'
    container_name: data-studio
    restart: always
    volumes:
    # add your local path of nginx conf file
      # - /home/johib/DX26-io/data-studio-react/nginx.conf:/etc/nginx/nginx.conf
      - /home/johib/DX26-io/data-studio-react/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # below code is commented for now.
    # environment:
    #   - NGINX_PROXY=http://localhost:8002
    #   - NGINX_PORT=80
    #   - NGINX_HOST=localhost
    build:
      context: '.'
      args:
        - API_URL=http://localhost:8002/
    ports:
      - 80:80
      - 443:443
