version: '3.3'
services:
  app:
    image: 'dx26io/data-studio:v1.0.9'
    container_name: data-studio
    restart: always
    volumes:
      # add your local path of nginx conf file
      # - /home/johib/DX26-io/data-studio-react/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
    # below code is commented for now.
    environment:
      - GATEWAY_HOST=localhost
      - GATEWAY_API_PORT=8002
      - GATEWAY_NETTY_SOCKET_IO_PORT=8085
    build:
      context: '.'
      args:
        - API_URL=http://localhost:8002/
        - NETTY_SOCKET_IO_URL=http://localhost:8085
    ports:
      - 80:80
      - 443:443
